AWSTemplateFormatVersion: 2010-09-09
Description: Create 1-VPC, 1-Subnet (1-Public)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Network Configuration"
        Parameters:
          - VPCCIDR
          - PublicSubnetACIDR
          - SubnetAAZ
    ParameterLabels:
      VPCCIDR:
        default: "VPC CIDER"
      SubnetAAZ:
        default: "Public SubnetA AZ"
      PublicSubnetACIDR:
        default: "PublicSubnetA CIDR"

Parameters:
  ProjectPrefix:
    Type: String

  VPCCIDR:
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

  SubnetAAZ:
    Type: AWS::EC2::AvailabilityZone::Name

  PublicSubnetACIDR:
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

Resources:
# ---------------------------------------------- #
#  VPC
# ---------------------------------------------- #
  # Create VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub ${ProjectPrefix}-vpc

  # Create Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProjectPrefix}-igw

  # Attach IGW
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

# ---------------------------------------------- #
#  Subnet
# ---------------------------------------------- #
# Create Public SubnetA
  PubSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref SubnetAAZ
      CidrBlock: !Ref PublicSubnetACIDR
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectPrefix}-pub-subnet-a

# ------------------------------------------------------------#
#  RouteTable
# ------------------------------------------------------------#
# Create Public RouteTableA
  PubRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectPrefix}-public-route-a

# ------------------------------------------------------------#
# Routing
# ------------------------------------------------------------#
# Create PublicRouteA
  PubRouteA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PubRouteTableA
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

# ------------------------------------------------------------#
# RouteTable Asscociation
# ------------------------------------------------------------#
# Associate PubRouteTable SubnetA
  PubSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSubnetA
      RouteTableId: !Ref PubRouteTableA

Outputs:
# VPC
  expVPC:
    Value: !Ref VPC
    Export:
      Name: VPC

  expVPCCIDR:
    Value: !Ref VPCCIDR
    Export:
      Name: VPCCIDR

# Default Security Group
  expDefaultSecurityGroup:
    Value: !GetAtt VPC.DefaultSecurityGroup
    Export:
      Name: DefaultSg

# Subnet
  expPubSubnetA:
    Value: !Ref PubSubnetA
    Export:
      Name: PubSubnetA

  expPubSubnetACIDR:
    Value: !Ref PublicSubnetACIDR
    Export:
      Name: PubSubnetACIDR